# Generated by Django 5.1.4 on 2024-12-12 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.recipient'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='newsletter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mailing.newsletter'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='server_response',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='status',
            field=models.CharField(choices=[('Успешно', 'Успешно'), ('Не успешно', 'Не успешно')], max_length=20),
        ),
    ]
