# Generated by Django 5.1.4 on 2024-12-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0006_message_owner_recipient_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipient",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
